print("=" * 60)
print(" CHÀO MỪNG ĐẾN VỚI KIOSK TỰ PHỤC VỤ")
print("=" * 60)

full_name = input(" Họ tên (VD: Nguyễn Văn A): ")
patient_id = input(" Mã bệnh nhân (VD: BN001): ")
body_temperature = float(input(" Nhiệt độ cơ thể (VD: 37.5): "))
heart_rate = int(input(" Nhịp tim (VD: 75): "))
weight = float(input(" Cân nặng (VD: 65.5): "))

print("\n" + "=" * 60)
print(" PHIẾU KHÁM BỆNH ĐIỆN TỬ")
print("=" * 60)
print(f"Bệnh nhân: {full_name}")
print(f"Mã BN: {patient_id}")
print(f"Nhiệt độ: {body_temperature}°C")
print(f"Nhịp tim: {heart_rate} nhịp/phút")
print(f"Cân nặng: {weight} kg")
print("=" * 60)
print(" Đã tiếp nhận thông tin!")

print("\n LOG HỆ THỐNG")
print("=" * 60)
print(f"full_name: {type(full_name)}")
print(f"patient_id: {type(patient_id)}")
print(f"body_temperature: {type(body_temperature)}")
print(f"heart_rate: {type(heart_rate)}")
print(f"weight: {type(weight)}")
print("=" * 60)
